/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CorporateClientRouteImport } from './routes/corporate-client'
import { Route as IndexRouteImport } from './routes/index'

const CorporateClientRoute = CorporateClientRouteImport.update({
  id: '/corporate-client',
  path: '/corporate-client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corporate-client': typeof CorporateClientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corporate-client': typeof CorporateClientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corporate-client': typeof CorporateClientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/corporate-client'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/corporate-client'
  id: '__root__' | '/' | '/corporate-client'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorporateClientRoute: typeof CorporateClientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/corporate-client': {
      id: '/corporate-client'
      path: '/corporate-client'
      fullPath: '/corporate-client'
      preLoaderRoute: typeof CorporateClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorporateClientRoute: CorporateClientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
